# Generated by Django 4.2.7 on 2024-12-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                    ("republished", "Republished"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
    ]
